# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/publictest/CLionProjects/dyld_patch

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/publictest/CLionProjects/dyld_patch

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/publictest/CLionProjects/dyld_patch/CMakeFiles /Users/publictest/CLionProjects/dyld_patch/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/publictest/CLionProjects/dyld_patch/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named dyld_patch

# Build rule for target.
dyld_patch: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dyld_patch
.PHONY : dyld_patch

# fast build rule for target.
dyld_patch/fast:
	$(MAKE) -f CMakeFiles/dyld_patch.dir/build.make CMakeFiles/dyld_patch.dir/build
.PHONY : dyld_patch/fast

code/ImageLoader.o: code/ImageLoader.cpp.o

.PHONY : code/ImageLoader.o

# target to build an object file
code/ImageLoader.cpp.o:
	$(MAKE) -f CMakeFiles/dyld_patch.dir/build.make CMakeFiles/dyld_patch.dir/code/ImageLoader.cpp.o
.PHONY : code/ImageLoader.cpp.o

code/ImageLoader.i: code/ImageLoader.cpp.i

.PHONY : code/ImageLoader.i

# target to preprocess a source file
code/ImageLoader.cpp.i:
	$(MAKE) -f CMakeFiles/dyld_patch.dir/build.make CMakeFiles/dyld_patch.dir/code/ImageLoader.cpp.i
.PHONY : code/ImageLoader.cpp.i

code/ImageLoader.s: code/ImageLoader.cpp.s

.PHONY : code/ImageLoader.s

# target to generate assembly for a file
code/ImageLoader.cpp.s:
	$(MAKE) -f CMakeFiles/dyld_patch.dir/build.make CMakeFiles/dyld_patch.dir/code/ImageLoader.cpp.s
.PHONY : code/ImageLoader.cpp.s

code/ImageLoaderMachO.o: code/ImageLoaderMachO.cpp.o

.PHONY : code/ImageLoaderMachO.o

# target to build an object file
code/ImageLoaderMachO.cpp.o:
	$(MAKE) -f CMakeFiles/dyld_patch.dir/build.make CMakeFiles/dyld_patch.dir/code/ImageLoaderMachO.cpp.o
.PHONY : code/ImageLoaderMachO.cpp.o

code/ImageLoaderMachO.i: code/ImageLoaderMachO.cpp.i

.PHONY : code/ImageLoaderMachO.i

# target to preprocess a source file
code/ImageLoaderMachO.cpp.i:
	$(MAKE) -f CMakeFiles/dyld_patch.dir/build.make CMakeFiles/dyld_patch.dir/code/ImageLoaderMachO.cpp.i
.PHONY : code/ImageLoaderMachO.cpp.i

code/ImageLoaderMachO.s: code/ImageLoaderMachO.cpp.s

.PHONY : code/ImageLoaderMachO.s

# target to generate assembly for a file
code/ImageLoaderMachO.cpp.s:
	$(MAKE) -f CMakeFiles/dyld_patch.dir/build.make CMakeFiles/dyld_patch.dir/code/ImageLoaderMachO.cpp.s
.PHONY : code/ImageLoaderMachO.cpp.s

code/ImageLoaderMachOClassic.o: code/ImageLoaderMachOClassic.cpp.o

.PHONY : code/ImageLoaderMachOClassic.o

# target to build an object file
code/ImageLoaderMachOClassic.cpp.o:
	$(MAKE) -f CMakeFiles/dyld_patch.dir/build.make CMakeFiles/dyld_patch.dir/code/ImageLoaderMachOClassic.cpp.o
.PHONY : code/ImageLoaderMachOClassic.cpp.o

code/ImageLoaderMachOClassic.i: code/ImageLoaderMachOClassic.cpp.i

.PHONY : code/ImageLoaderMachOClassic.i

# target to preprocess a source file
code/ImageLoaderMachOClassic.cpp.i:
	$(MAKE) -f CMakeFiles/dyld_patch.dir/build.make CMakeFiles/dyld_patch.dir/code/ImageLoaderMachOClassic.cpp.i
.PHONY : code/ImageLoaderMachOClassic.cpp.i

code/ImageLoaderMachOClassic.s: code/ImageLoaderMachOClassic.cpp.s

.PHONY : code/ImageLoaderMachOClassic.s

# target to generate assembly for a file
code/ImageLoaderMachOClassic.cpp.s:
	$(MAKE) -f CMakeFiles/dyld_patch.dir/build.make CMakeFiles/dyld_patch.dir/code/ImageLoaderMachOClassic.cpp.s
.PHONY : code/ImageLoaderMachOClassic.cpp.s

code/ImageLoaderMachOCompressed.o: code/ImageLoaderMachOCompressed.cpp.o

.PHONY : code/ImageLoaderMachOCompressed.o

# target to build an object file
code/ImageLoaderMachOCompressed.cpp.o:
	$(MAKE) -f CMakeFiles/dyld_patch.dir/build.make CMakeFiles/dyld_patch.dir/code/ImageLoaderMachOCompressed.cpp.o
.PHONY : code/ImageLoaderMachOCompressed.cpp.o

code/ImageLoaderMachOCompressed.i: code/ImageLoaderMachOCompressed.cpp.i

.PHONY : code/ImageLoaderMachOCompressed.i

# target to preprocess a source file
code/ImageLoaderMachOCompressed.cpp.i:
	$(MAKE) -f CMakeFiles/dyld_patch.dir/build.make CMakeFiles/dyld_patch.dir/code/ImageLoaderMachOCompressed.cpp.i
.PHONY : code/ImageLoaderMachOCompressed.cpp.i

code/ImageLoaderMachOCompressed.s: code/ImageLoaderMachOCompressed.cpp.s

.PHONY : code/ImageLoaderMachOCompressed.s

# target to generate assembly for a file
code/ImageLoaderMachOCompressed.cpp.s:
	$(MAKE) -f CMakeFiles/dyld_patch.dir/build.make CMakeFiles/dyld_patch.dir/code/ImageLoaderMachOCompressed.cpp.s
.PHONY : code/ImageLoaderMachOCompressed.cpp.s

code/dyld.o: code/dyld.cpp.o

.PHONY : code/dyld.o

# target to build an object file
code/dyld.cpp.o:
	$(MAKE) -f CMakeFiles/dyld_patch.dir/build.make CMakeFiles/dyld_patch.dir/code/dyld.cpp.o
.PHONY : code/dyld.cpp.o

code/dyld.i: code/dyld.cpp.i

.PHONY : code/dyld.i

# target to preprocess a source file
code/dyld.cpp.i:
	$(MAKE) -f CMakeFiles/dyld_patch.dir/build.make CMakeFiles/dyld_patch.dir/code/dyld.cpp.i
.PHONY : code/dyld.cpp.i

code/dyld.s: code/dyld.cpp.s

.PHONY : code/dyld.s

# target to generate assembly for a file
code/dyld.cpp.s:
	$(MAKE) -f CMakeFiles/dyld_patch.dir/build.make CMakeFiles/dyld_patch.dir/code/dyld.cpp.s
.PHONY : code/dyld.cpp.s

code/dyldAPIs.o: code/dyldAPIs.cpp.o

.PHONY : code/dyldAPIs.o

# target to build an object file
code/dyldAPIs.cpp.o:
	$(MAKE) -f CMakeFiles/dyld_patch.dir/build.make CMakeFiles/dyld_patch.dir/code/dyldAPIs.cpp.o
.PHONY : code/dyldAPIs.cpp.o

code/dyldAPIs.i: code/dyldAPIs.cpp.i

.PHONY : code/dyldAPIs.i

# target to preprocess a source file
code/dyldAPIs.cpp.i:
	$(MAKE) -f CMakeFiles/dyld_patch.dir/build.make CMakeFiles/dyld_patch.dir/code/dyldAPIs.cpp.i
.PHONY : code/dyldAPIs.cpp.i

code/dyldAPIs.s: code/dyldAPIs.cpp.s

.PHONY : code/dyldAPIs.s

# target to generate assembly for a file
code/dyldAPIs.cpp.s:
	$(MAKE) -f CMakeFiles/dyld_patch.dir/build.make CMakeFiles/dyld_patch.dir/code/dyldAPIs.cpp.s
.PHONY : code/dyldAPIs.cpp.s

code/dyldInitialization.o: code/dyldInitialization.cpp.o

.PHONY : code/dyldInitialization.o

# target to build an object file
code/dyldInitialization.cpp.o:
	$(MAKE) -f CMakeFiles/dyld_patch.dir/build.make CMakeFiles/dyld_patch.dir/code/dyldInitialization.cpp.o
.PHONY : code/dyldInitialization.cpp.o

code/dyldInitialization.i: code/dyldInitialization.cpp.i

.PHONY : code/dyldInitialization.i

# target to preprocess a source file
code/dyldInitialization.cpp.i:
	$(MAKE) -f CMakeFiles/dyld_patch.dir/build.make CMakeFiles/dyld_patch.dir/code/dyldInitialization.cpp.i
.PHONY : code/dyldInitialization.cpp.i

code/dyldInitialization.s: code/dyldInitialization.cpp.s

.PHONY : code/dyldInitialization.s

# target to generate assembly for a file
code/dyldInitialization.cpp.s:
	$(MAKE) -f CMakeFiles/dyld_patch.dir/build.make CMakeFiles/dyld_patch.dir/code/dyldInitialization.cpp.s
.PHONY : code/dyldInitialization.cpp.s

code/dyldLibSystemGlue.o: code/dyldLibSystemGlue.cpp.o

.PHONY : code/dyldLibSystemGlue.o

# target to build an object file
code/dyldLibSystemGlue.cpp.o:
	$(MAKE) -f CMakeFiles/dyld_patch.dir/build.make CMakeFiles/dyld_patch.dir/code/dyldLibSystemGlue.cpp.o
.PHONY : code/dyldLibSystemGlue.cpp.o

code/dyldLibSystemGlue.i: code/dyldLibSystemGlue.cpp.i

.PHONY : code/dyldLibSystemGlue.i

# target to preprocess a source file
code/dyldLibSystemGlue.cpp.i:
	$(MAKE) -f CMakeFiles/dyld_patch.dir/build.make CMakeFiles/dyld_patch.dir/code/dyldLibSystemGlue.cpp.i
.PHONY : code/dyldLibSystemGlue.cpp.i

code/dyldLibSystemGlue.s: code/dyldLibSystemGlue.cpp.s

.PHONY : code/dyldLibSystemGlue.s

# target to generate assembly for a file
code/dyldLibSystemGlue.cpp.s:
	$(MAKE) -f CMakeFiles/dyld_patch.dir/build.make CMakeFiles/dyld_patch.dir/code/dyldLibSystemGlue.cpp.s
.PHONY : code/dyldLibSystemGlue.cpp.s

code/dyldLock.o: code/dyldLock.cpp.o

.PHONY : code/dyldLock.o

# target to build an object file
code/dyldLock.cpp.o:
	$(MAKE) -f CMakeFiles/dyld_patch.dir/build.make CMakeFiles/dyld_patch.dir/code/dyldLock.cpp.o
.PHONY : code/dyldLock.cpp.o

code/dyldLock.i: code/dyldLock.cpp.i

.PHONY : code/dyldLock.i

# target to preprocess a source file
code/dyldLock.cpp.i:
	$(MAKE) -f CMakeFiles/dyld_patch.dir/build.make CMakeFiles/dyld_patch.dir/code/dyldLock.cpp.i
.PHONY : code/dyldLock.cpp.i

code/dyldLock.s: code/dyldLock.cpp.s

.PHONY : code/dyldLock.s

# target to generate assembly for a file
code/dyldLock.cpp.s:
	$(MAKE) -f CMakeFiles/dyld_patch.dir/build.make CMakeFiles/dyld_patch.dir/code/dyldLock.cpp.s
.PHONY : code/dyldLock.cpp.s

code/dyldStartup.o: code/dyldStartup.s.o

.PHONY : code/dyldStartup.o

# target to build an object file
code/dyldStartup.s.o:
	$(MAKE) -f CMakeFiles/dyld_patch.dir/build.make CMakeFiles/dyld_patch.dir/code/dyldStartup.s.o
.PHONY : code/dyldStartup.s.o

code/dyld_gdb.o: code/dyld_gdb.cpp.o

.PHONY : code/dyld_gdb.o

# target to build an object file
code/dyld_gdb.cpp.o:
	$(MAKE) -f CMakeFiles/dyld_patch.dir/build.make CMakeFiles/dyld_patch.dir/code/dyld_gdb.cpp.o
.PHONY : code/dyld_gdb.cpp.o

code/dyld_gdb.i: code/dyld_gdb.cpp.i

.PHONY : code/dyld_gdb.i

# target to preprocess a source file
code/dyld_gdb.cpp.i:
	$(MAKE) -f CMakeFiles/dyld_patch.dir/build.make CMakeFiles/dyld_patch.dir/code/dyld_gdb.cpp.i
.PHONY : code/dyld_gdb.cpp.i

code/dyld_gdb.s: code/dyld_gdb.cpp.s

.PHONY : code/dyld_gdb.s

# target to generate assembly for a file
code/dyld_gdb.cpp.s:
	$(MAKE) -f CMakeFiles/dyld_patch.dir/build.make CMakeFiles/dyld_patch.dir/code/dyld_gdb.cpp.s
.PHONY : code/dyld_gdb.cpp.s

code/dyld_process_info.o: code/dyld_process_info.cpp.o

.PHONY : code/dyld_process_info.o

# target to build an object file
code/dyld_process_info.cpp.o:
	$(MAKE) -f CMakeFiles/dyld_patch.dir/build.make CMakeFiles/dyld_patch.dir/code/dyld_process_info.cpp.o
.PHONY : code/dyld_process_info.cpp.o

code/dyld_process_info.i: code/dyld_process_info.cpp.i

.PHONY : code/dyld_process_info.i

# target to preprocess a source file
code/dyld_process_info.cpp.i:
	$(MAKE) -f CMakeFiles/dyld_patch.dir/build.make CMakeFiles/dyld_patch.dir/code/dyld_process_info.cpp.i
.PHONY : code/dyld_process_info.cpp.i

code/dyld_process_info.s: code/dyld_process_info.cpp.s

.PHONY : code/dyld_process_info.s

# target to generate assembly for a file
code/dyld_process_info.cpp.s:
	$(MAKE) -f CMakeFiles/dyld_patch.dir/build.make CMakeFiles/dyld_patch.dir/code/dyld_process_info.cpp.s
.PHONY : code/dyld_process_info.cpp.s

code/dyld_process_info_notify.o: code/dyld_process_info_notify.cpp.o

.PHONY : code/dyld_process_info_notify.o

# target to build an object file
code/dyld_process_info_notify.cpp.o:
	$(MAKE) -f CMakeFiles/dyld_patch.dir/build.make CMakeFiles/dyld_patch.dir/code/dyld_process_info_notify.cpp.o
.PHONY : code/dyld_process_info_notify.cpp.o

code/dyld_process_info_notify.i: code/dyld_process_info_notify.cpp.i

.PHONY : code/dyld_process_info_notify.i

# target to preprocess a source file
code/dyld_process_info_notify.cpp.i:
	$(MAKE) -f CMakeFiles/dyld_patch.dir/build.make CMakeFiles/dyld_patch.dir/code/dyld_process_info_notify.cpp.i
.PHONY : code/dyld_process_info_notify.cpp.i

code/dyld_process_info_notify.s: code/dyld_process_info_notify.cpp.s

.PHONY : code/dyld_process_info_notify.s

# target to generate assembly for a file
code/dyld_process_info_notify.cpp.s:
	$(MAKE) -f CMakeFiles/dyld_patch.dir/build.make CMakeFiles/dyld_patch.dir/code/dyld_process_info_notify.cpp.s
.PHONY : code/dyld_process_info_notify.cpp.s

code/dyld_stub_binder.o: code/dyld_stub_binder.s.o

.PHONY : code/dyld_stub_binder.o

# target to build an object file
code/dyld_stub_binder.s.o:
	$(MAKE) -f CMakeFiles/dyld_patch.dir/build.make CMakeFiles/dyld_patch.dir/code/dyld_stub_binder.s.o
.PHONY : code/dyld_stub_binder.s.o

code/glue.o: code/glue.cpp.o

.PHONY : code/glue.o

# target to build an object file
code/glue.cpp.o:
	$(MAKE) -f CMakeFiles/dyld_patch.dir/build.make CMakeFiles/dyld_patch.dir/code/glue.cpp.o
.PHONY : code/glue.cpp.o

code/glue.i: code/glue.cpp.i

.PHONY : code/glue.i

# target to preprocess a source file
code/glue.cpp.i:
	$(MAKE) -f CMakeFiles/dyld_patch.dir/build.make CMakeFiles/dyld_patch.dir/code/glue.cpp.i
.PHONY : code/glue.cpp.i

code/glue.s: code/glue.cpp.s

.PHONY : code/glue.s

# target to generate assembly for a file
code/glue.cpp.s:
	$(MAKE) -f CMakeFiles/dyld_patch.dir/build.make CMakeFiles/dyld_patch.dir/code/glue.cpp.s
.PHONY : code/glue.cpp.s

code/start_glue.o: code/start_glue.s.o

.PHONY : code/start_glue.o

# target to build an object file
code/start_glue.s.o:
	$(MAKE) -f CMakeFiles/dyld_patch.dir/build.make CMakeFiles/dyld_patch.dir/code/start_glue.s.o
.PHONY : code/start_glue.s.o

code/threadLocalHelpers.o: code/threadLocalHelpers.s.o

.PHONY : code/threadLocalHelpers.o

# target to build an object file
code/threadLocalHelpers.s.o:
	$(MAKE) -f CMakeFiles/dyld_patch.dir/build.make CMakeFiles/dyld_patch.dir/code/threadLocalHelpers.s.o
.PHONY : code/threadLocalHelpers.s.o

code/threadLocalVariables.o: code/threadLocalVariables.cpp.o

.PHONY : code/threadLocalVariables.o

# target to build an object file
code/threadLocalVariables.cpp.o:
	$(MAKE) -f CMakeFiles/dyld_patch.dir/build.make CMakeFiles/dyld_patch.dir/code/threadLocalVariables.cpp.o
.PHONY : code/threadLocalVariables.cpp.o

code/threadLocalVariables.i: code/threadLocalVariables.cpp.i

.PHONY : code/threadLocalVariables.i

# target to preprocess a source file
code/threadLocalVariables.cpp.i:
	$(MAKE) -f CMakeFiles/dyld_patch.dir/build.make CMakeFiles/dyld_patch.dir/code/threadLocalVariables.cpp.i
.PHONY : code/threadLocalVariables.cpp.i

code/threadLocalVariables.s: code/threadLocalVariables.cpp.s

.PHONY : code/threadLocalVariables.s

# target to generate assembly for a file
code/threadLocalVariables.cpp.s:
	$(MAKE) -f CMakeFiles/dyld_patch.dir/build.make CMakeFiles/dyld_patch.dir/code/threadLocalVariables.cpp.s
.PHONY : code/threadLocalVariables.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/dyld_patch.dir/build.make CMakeFiles/dyld_patch.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/dyld_patch.dir/build.make CMakeFiles/dyld_patch.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/dyld_patch.dir/build.make CMakeFiles/dyld_patch.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... dyld_patch"
	@echo "... code/ImageLoader.o"
	@echo "... code/ImageLoader.i"
	@echo "... code/ImageLoader.s"
	@echo "... code/ImageLoaderMachO.o"
	@echo "... code/ImageLoaderMachO.i"
	@echo "... code/ImageLoaderMachO.s"
	@echo "... code/ImageLoaderMachOClassic.o"
	@echo "... code/ImageLoaderMachOClassic.i"
	@echo "... code/ImageLoaderMachOClassic.s"
	@echo "... code/ImageLoaderMachOCompressed.o"
	@echo "... code/ImageLoaderMachOCompressed.i"
	@echo "... code/ImageLoaderMachOCompressed.s"
	@echo "... code/dyld.o"
	@echo "... code/dyld.i"
	@echo "... code/dyld.s"
	@echo "... code/dyldAPIs.o"
	@echo "... code/dyldAPIs.i"
	@echo "... code/dyldAPIs.s"
	@echo "... code/dyldInitialization.o"
	@echo "... code/dyldInitialization.i"
	@echo "... code/dyldInitialization.s"
	@echo "... code/dyldLibSystemGlue.o"
	@echo "... code/dyldLibSystemGlue.i"
	@echo "... code/dyldLibSystemGlue.s"
	@echo "... code/dyldLock.o"
	@echo "... code/dyldLock.i"
	@echo "... code/dyldLock.s"
	@echo "... code/dyldStartup.o"
	@echo "... code/dyld_gdb.o"
	@echo "... code/dyld_gdb.i"
	@echo "... code/dyld_gdb.s"
	@echo "... code/dyld_process_info.o"
	@echo "... code/dyld_process_info.i"
	@echo "... code/dyld_process_info.s"
	@echo "... code/dyld_process_info_notify.o"
	@echo "... code/dyld_process_info_notify.i"
	@echo "... code/dyld_process_info_notify.s"
	@echo "... code/dyld_stub_binder.o"
	@echo "... code/glue.o"
	@echo "... code/glue.i"
	@echo "... code/glue.s"
	@echo "... code/start_glue.o"
	@echo "... code/threadLocalHelpers.o"
	@echo "... code/threadLocalVariables.o"
	@echo "... code/threadLocalVariables.i"
	@echo "... code/threadLocalVariables.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

